Document: helloaliben
Title: Debian helloaliben Manual
Author: <insert document author here>
Abstract: This manual describes what helloaliben is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/helloaliben/helloaliben.sgml.gz

Format: postscript
Files: /usr/share/doc/helloaliben/helloaliben.ps.gz

Format: text
Files: /usr/share/doc/helloaliben/helloaliben.text.gz

Format: HTML
Index: /usr/share/doc/helloaliben/html/index.html
Files: /usr/share/doc/helloaliben/html/*.html
